# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check links stemming from documentation
        run: make -C docs linkcheck 

      # Runs a set of commands using the runners shell
      - name: Generate HTML tarball
        run: |
          make -C docs html 
          tar -acvf html-docs.tgz -C docs/build html

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: HTML documentation
          path: html-docs.tgz
